# CI for Citygis Project 56 - Nav Appaiya 21 January 2016
language: php

php:
  - 5.3

branches:
  only:
    - master

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - composer self-update
  - composer install --dev --prefer-dist
  - app/console do:da:cr -e=test > /dev/null
  - app/console do:sc:cr -e=test > /dev/null
  - chmod -R 777 app/cache app/logs
  - app/console --env=test cache:warmup
  - chmod -R 777 app/cache app/logs

  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && unzip chromedriver_linux32_23.0.1240.0.zip && sudo mv chromedriver /usr/bin"
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.28.0.jar"
  - "java -jar selenium-server-standalone-2.28.0.jar > /dev/null &"
  - sleep 5

script:
    - bin/behat @AppBundle

notifications:
    email:
        - navarajh@gmail.com