CREATE TABLE connections (id INT AUTO_INCREMENT NOT NULL, port VARCHAR(255) DEFAULT NULL, value INT NOT NULL, dateTime DATETIME DEFAULT NULL, unitId INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER
SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;


CREATE TABLE events (id INT AUTO_INCREMENT NOT NULL, port VARCHAR(255) DEFAULT NULL, value INT DEFAULT NULL, unitId INT DEFAULT NULL, dateTime DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER
SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;


CREATE TABLE monitoring (id INT AUTO_INCREMENT NOT NULL, beginTime DATETIME NOT NULL, endTime DATE DEFAULT NULL, unitId INT DEFAULT NULL, TYPE VARCHAR(255) DEFAULT NULL, MIN NUMERIC(10, 0) DEFAULT NULL, MAX NUMERIC(10, 0) DEFAULT NULL, SUM NUMERIC(10, 0) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, enabled TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER
SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;


CREATE TABLE positions (id INT AUTO_INCREMENT NOT NULL, unitId INT DEFAULT NULL, rDx NUMERIC(10, 0) DEFAULT NULL, rDy NUMERIC(10, 0) DEFAULT NULL, speed NUMERIC(10, 0) DEFAULT NULL, course NUMERIC(10, 0) DEFAULT NULL, numSattellites INT DEFAULT NULL, hdop INT NOT NULL, quality VARCHAR(255) NOT NULL, dateTime DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER
SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;