anno:
    resource: '@AppBundle/Controller/'
    type:     annotation

app:
    path:       /
    defaults:   { _controller: AppBundle:Default:index }

dashboard:
    path:      /dashboard
    defaults:  { _controller: AppBundle:Dashboard:index }

# Page location (voorbeeld voor xdg) => Pagina's worden: location, event, position, en monitoring (letop! enkelvoud!)
location:
    path:      /location
    defaults:  { _controller: AppBundle:Dashboard:location }
    
event:
    path:      /event
    defaults:  { _controller: AppBundle:Dashboard:event }
    
position:
    path:      /position
    defaults:  { _controller: AppBundle:Dashboard:position }

monitoring:
    path:      /monitoring
    defaults:  { _controller: AppBundle:Dashboard:monitoring }

status:
    path:      /status
    defaults:  { _controller: AppBundle:Systemstatus:index }

settings:
    path:      /settings
    defaults:  { _controller: AppBundle:Settings:index }


login:
    path:       /login
    defaults:   { _controller: AppBundle:Login:index }

register:
    path:       /register
    defaults:   { _controller: AppBundle:Login:register }