app:
    path:       /
    defaults:   { _controller: AppBundle:Default:index }

login:
    path:       /login
    defaults:   { _controller: AppBundle:Login:index }

register:
    path:       /register
    defaults:   { _controller: AppBundle:Login:register }

test:
    path:      /test
    defaults:  { _controller: AppBundle:Api:root }