
app:
    path:       /
    defaults:   { _controller: AppBundle:Default:index }

dashboard:
    path:      /dashboard
    defaults:  { _controller: AppBundle:Dashboard:index }

monitoring:
    path:      /monitoring
    defaults:  { _controller: AppBundle:Monitor:index }

status:
    path:      /status
    defaults:  { _controller: AppBundle:Systemstatus:index }


settings:
    path:      /settings
    defaults:  { _controller: AppBundle:Settings:index }


login:
    path:       /login
    defaults:   { _controller: AppBundle:Login:index }

register:
    path:       /register
    defaults:   { _controller: AppBundle:Login:register }